In [1]:
import numpy as np

In [2]:
arr = np.random.randn(100)
arr

array([ 0.80855947, -0.02231233, -1.68030131, -1.01682969,  0.87660893,
        1.27309139,  1.62469502, -0.67422829, -0.37378009,  1.16111539,
        0.49673903, -0.27547573,  1.52232676,  0.72677405, -0.33007123,
        2.06935171, -0.41057248, -0.889008  , -0.89031637,  1.41079852,
        0.14589781,  0.16123028, -0.74213669, -0.02361728, -0.90400797,
        1.72985665, -0.63140824,  0.56704875,  0.17132026, -1.57773962,
        1.10645165, -2.21579463, -0.94434045, -1.19697554,  0.36508187,
       -0.41190229,  1.21796124,  0.8397796 ,  2.10069146,  0.43419942,
       -0.55530154, -0.17326999,  0.40240109, -1.47798232,  0.53682323,
        0.41002406,  0.87483881,  1.10937126, -0.02038259, -1.27290685,
       -1.38765149,  0.11846194,  0.40783842,  2.49128487,  0.23216262,
        0.26262849,  1.34194605,  0.61437783, -0.40965   ,  1.35476927,
        0.93304949, -2.40355305,  0.81035599, -0.84505236,  1.07880197,
       -0.24796018, -0.12535044, -0.72407228, -0.68553204,  0.40

In [3]:
(arr > 0).sum()

48

In [4]:
bools = np.array([False, False, True, False])
bools

array([False, False,  True, False])

In [6]:
bools.any()    #checking for True value.

True

In [7]:
bools.all()       #checking for True value.

False

In [8]:
arr = np.random.randn(5, 3)
arr

array([[ 0.45808369,  0.11438725, -1.00435405],
       [-1.25273202, -0.91974129,  0.92815024],
       [-0.12390053,  0.93936977,  0.13852787],
       [ 0.70613742,  1.17277994, -0.79786963],
       [ 1.68778218, -0.0406847 , -0.95364993]])

In [9]:
arr.sort(1)

In [11]:
arr1=arr
arr1

array([[-1.00435405,  0.11438725,  0.45808369],
       [-1.25273202, -0.91974129,  0.92815024],
       [-0.12390053,  0.13852787,  0.93936977],
       [-0.79786963,  0.70613742,  1.17277994],
       [-0.95364993, -0.0406847 ,  1.68778218]])

In [12]:
arr1.shape

(5, 3)

In [13]:
arr.sort(0)

In [14]:
arr2=arr
arr2

array([[-1.25273202, -0.91974129,  0.45808369],
       [-1.00435405, -0.0406847 ,  0.92815024],
       [-0.95364993,  0.11438725,  0.93936977],
       [-0.79786963,  0.13852787,  1.17277994],
       [-0.12390053,  0.70613742,  1.68778218]])

In [32]:
large_arr = np.random.randn(1000)
large_arr

array([ 7.03182154e-01,  1.00429454e-01, -3.87441477e-01, -1.72397435e-01,
       -7.11079137e-01,  1.81943300e+00,  2.55654816e+00,  4.68535554e-01,
       -1.28327985e+00,  1.56575983e+00,  1.94082447e+00, -1.60455650e+00,
       -9.94975817e-01, -5.83805090e-01, -1.41420582e+00, -5.32942580e-01,
       -7.42280381e-01,  1.25803134e+00, -8.17523329e-01,  5.04378448e-01,
       -1.44725255e+00, -4.31432985e-01, -6.67609302e-02, -2.54660313e-01,
        5.18493593e-01, -1.51787003e+00, -6.81510742e-01,  7.87596472e-01,
        8.45575208e-01,  6.34122705e-01,  8.26309674e-02,  3.64350189e-01,
        1.41864072e+00,  4.50138553e-01,  6.41743688e-01,  1.95423539e+00,
       -4.22952150e-01, -4.29081007e-01,  4.25772727e-01,  8.88686893e-01,
        2.26972618e-01,  7.71155676e-01,  9.26566403e-01, -5.16937351e-01,
       -8.56529049e-01, -2.20002414e+00,  1.91690153e+00,  7.77858514e-01,
       -5.77959990e-01, -5.80628551e-01,  7.81237046e-01,  1.44315926e+00,
       -4.90355935e-02,  

In [33]:
large_arr.sort()

In [34]:
large_arr

array([-3.10034967e+00, -2.86710896e+00, -2.83579988e+00, -2.70449757e+00,
       -2.55360457e+00, -2.52390148e+00, -2.41448160e+00, -2.24218291e+00,
       -2.23595471e+00, -2.20002414e+00, -2.19569552e+00, -2.18967741e+00,
       -2.14753521e+00, -2.14153655e+00, -2.12652867e+00, -2.12010490e+00,
       -2.08460301e+00, -2.03560436e+00, -2.00225735e+00, -1.99300530e+00,
       -1.99028481e+00, -1.98694369e+00, -1.96170827e+00, -1.94250752e+00,
       -1.93980669e+00, -1.91029739e+00, -1.90850664e+00, -1.89953780e+00,
       -1.87987206e+00, -1.84077898e+00, -1.83417405e+00, -1.81761939e+00,
       -1.80809057e+00, -1.78481678e+00, -1.77552570e+00, -1.77184605e+00,
       -1.75212838e+00, -1.74893556e+00, -1.65570189e+00, -1.65249383e+00,
       -1.65156275e+00, -1.64377842e+00, -1.64304075e+00, -1.64296051e+00,
       -1.63857751e+00, -1.63549975e+00, -1.61232080e+00, -1.61063967e+00,
       -1.60624642e+00, -1.60455650e+00, -1.59532849e+00, -1.58615550e+00,
       -1.58215776e+00, -

In [35]:
np.unique(large_arr)

array([-3.10034967e+00, -2.86710896e+00, -2.83579988e+00, -2.70449757e+00,
       -2.55360457e+00, -2.52390148e+00, -2.41448160e+00, -2.24218291e+00,
       -2.23595471e+00, -2.20002414e+00, -2.19569552e+00, -2.18967741e+00,
       -2.14753521e+00, -2.14153655e+00, -2.12652867e+00, -2.12010490e+00,
       -2.08460301e+00, -2.03560436e+00, -2.00225735e+00, -1.99300530e+00,
       -1.99028481e+00, -1.98694369e+00, -1.96170827e+00, -1.94250752e+00,
       -1.93980669e+00, -1.91029739e+00, -1.90850664e+00, -1.89953780e+00,
       -1.87987206e+00, -1.84077898e+00, -1.83417405e+00, -1.81761939e+00,
       -1.80809057e+00, -1.78481678e+00, -1.77552570e+00, -1.77184605e+00,
       -1.75212838e+00, -1.74893556e+00, -1.65570189e+00, -1.65249383e+00,
       -1.65156275e+00, -1.64377842e+00, -1.64304075e+00, -1.64296051e+00,
       -1.63857751e+00, -1.63549975e+00, -1.61232080e+00, -1.61063967e+00,
       -1.60624642e+00, -1.60455650e+00, -1.59532849e+00, -1.58615550e+00,
       -1.58215776e+00, -

In [36]:
np.repeat(5,10)     # np.repeat(value,times)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [39]:
np.repeat(('ALI', 'Hassan',10), 6)    #value may be string or integar.   But 'no of times' refers to INT value.

array(['ALI', 'ALI', 'ALI', 'ALI', 'ALI', 'ALI', 'Hassan', 'Hassan',
       'Hassan', 'Hassan', 'Hassan', 'Hassan', '10', '10', '10', '10',
       '10', '10'], dtype='<U6')

In [28]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [40]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
values

array([6, 0, 0, 3, 2, 5, 6])

In [42]:
var1=[2, 3, 6]
var1

[2, 3, 6]

In [44]:
 np.in1d(values,var1)

array([ True, False, False,  True,  True, False,  True])

In [47]:
x= np.random.randn(10)
y=np.random.randn(10)
print(x)
print(y)

[ 0.14835415  0.39070904  1.61776137  1.08437173 -2.06056327 -0.05818185
 -0.23512028  0.77145222 -0.29275484  0.22291637]
[ 1.50012689 -0.34107953  1.3960174  -0.81180408 -1.00537637 -0.53343844
  0.78272348  0.21744985 -0.80081475 -1.34598264]


In [48]:
 np.in1d(x,y)

array([False, False, False, False, False, False, False, False, False,
       False])

In [51]:
x1= np.arange(10)
y1=np.arange(10)
print(x1)
print(y1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [52]:
 np.in1d(x1,y1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [53]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.save('New_array',arr1)

In [60]:
np.load('New_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.save()
# np.svez()
# np.savez_compressed()
# np.safe_eval
# np.safe_evaluate()

In [61]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [63]:
print(x.shape)
print(y.shape)

(2, 3)
(3, 2)


In [64]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [65]:
x.dot(y)     # x.dot(y) is equivalent to np.dot(x, y):

array([[ 28.,  64.],
       [ 67., 181.]])

In [67]:
# A matrix product between a two-dimensional array and a suitably sized 
# onedimensional array results in a one-dimensional array:
one=np.ones(3)
print(one)
print(x)
np.dot(x, one)    # X is 2d while 'one' is 1d.


[1. 1. 1.]
[[1. 2. 3.]
 [4. 5. 6.]]


array([ 6., 15.])

In [68]:
x @ np.ones(3)       # The @ symbol (as of Python 3.5) also works as an "infix operator" that performs matrix
                     # multiplication:    # One matrix is must for @ operator to perform action.

array([ 6., 15.])

In [69]:
np.ones(6) @ np.ones(9)

ValueError: ignored

In [73]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
mat

array([[ 0.69135742,  0.60027162, -0.59349006,  0.36220258,  0.1901248 ],
       [ 0.60027162,  4.34243097, -1.91310201,  0.17669495,  1.82853167],
       [-0.59349006, -1.91310201, 10.711614  ,  2.88017853, -1.66206854],
       [ 0.36220258,  0.17669495,  2.88017853,  1.81553884, -0.73319714],
       [ 0.1901248 ,  1.82853167, -1.66206854, -0.73319714,  1.3521212 ]])

In [75]:
inv(mat)

array([[ 4.35398108,  1.82845702,  1.14498638, -4.5331294 , -4.13559303],
       [ 1.82845702,  2.37331035,  0.83303446, -3.71791783, -4.45870867],
       [ 1.14498638,  0.83303446,  0.54766307, -1.82636789, -1.60470404],
       [-4.5331294 , -3.71791783, -1.82636789,  7.80478814,  7.65248748],
       [-4.13559303, -4.45870867, -1.60470404,  7.65248748,  9.52786085]])

In [76]:
q, r = qr(mat)


In [77]:
q

array([[-0.59329895,  0.52323508, -0.2017255 ,  0.49293721, -0.30090055],
       [-0.51513228, -0.704192  , -0.30798871, -0.19660481, -0.32441004],
       [ 0.50931258, -0.025393  , -0.81970895,  0.23324046, -0.11675625],
       [-0.31082968,  0.31589644, -0.43842528, -0.54896964,  0.55678537],
       [-0.16315851, -0.36042103, -0.01761495,  0.60215503,  0.69323518]])

In [78]:
r

array([[-1.16527666, -3.92069634,  6.16911299,  0.71629945, -1.89395958],
       [ 0.        , -3.29846653,  2.27353895,  0.82973549, -1.86489979],
       [ 0.        ,  0.        , -9.30493578, -3.27145656,  1.05852694],
       [ 0.        ,  0.        ,  0.        , -0.62259584,  0.5632494 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.07275874]])