In [1]:
import numpy as np

In [2]:
# variable_name[row]            # indexing
# variable_name[row,column]     #   indexing
# variable_name[start_row_index:end_row_index]   # only slicing of a row
# variable_name[start_row_index:end_row_index,start_column_index:end_column_index]   #Slicing of both rows and columns

In [3]:
# 1  #when we use a single num it's means that we are talking about indexing
# 2  #when we use two index seprated by a comma its mean we are also
     #talking about indexing.
    
# 3  #when we use colan(:) sign its mean we are talking about slicing.

# 4  #when we use colon(:)sign providing index before comma,it;s mean we are
     #talking about slicing of only rows.

# 5  #when we use colon(:)sign providing index before and after comma(,) it;s mean we are
     #talking about slicing of both rows and columns.

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [6]:
arr2d[1,1]

5

In [7]:
arr2d[2]

array([7, 8, 9])

In [8]:
arr2d[2,0:1]

array([7])

In [9]:
arr2d[2:,0:1]

array([[7]])

In [10]:
arr2d[0:1]     # variable_name[starting_index_row:ending_index_row, starting_index_co;umn:ending_index_column]

array([[1, 2, 3]])

In [11]:
arr2d[0]   #   variable_name[starting_index_row: ending_index_row]

array([1, 2, 3])

In [12]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [13]:
arr2d[1,:2]   #only select row having index 1, but also select column starting from 0 to 1.  
              # where index 2 column is exclusive.

array([4, 5])

In [14]:
arr2d[1:2,:2]   #in rows, index 2 row is exclusive, where column index starts from 0 to 1.
                # 2 index of column is exclusive.

array([[4, 5]])