In [1]:
import numpy as np

In [20]:
arr = np.empty((8, 4))
arr


array([[4.63790412e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [21]:
arr[[4, 3, 0, 6]]   # we can print out a row of our desire also with our desire order.

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [4.63790412e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [18]:
arr[[0,3,4,6]]   # we should have to use sq bracket to get desire row of desire order.

array([[4.63790412e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [22]:
arr[[-4, -3, 0, -6]]  # we can also use negative index of row/column to get desired row/column respectively.

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [4.63790412e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [25]:
for i in range(8):   # update values through Looping.
  arr[i]= 4

In [26]:
arr

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
for i in range(8):
  arr[i]= 0

In [28]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arr2d = np.arange(32).reshape((8, 4))
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


In [31]:
variable_name[[Multiple Desired indexes for rows] , [Multiple Desired indexes for Columns]]
arr2d[[1,5,7,2]  ,  [0,3,1,2]]    #we can provide row and column indexes to get intersected value.

array([ 4, 23, 29, 10])

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [35]:
print(arr2d)
print(arr2d[[1,5,7,2]][:,[0,3,1,2]])   # when we give multiple index pf rows or we select rows
                                        but when we provide indexs of columns. Actually they 
                                        are not only indexs of columns, but also they target position
                                        of elements against that (Row's index).
                                        variable_name[[1,5,7,2]][:,[0,3,1,2]]  original expression
                                        variable_name[[1,5,7,2]][:,[0,3,1,2]]   Row=1, column=0,3,1,2 (index as a desired value)
                                        variable_name[[1,5,7,2]][:,[0,3,1,2]]   Row=5, column=0,3,1,2
                                        variable_name[[1,5,7,2]][:,[0,3,1,2]]   Row=7, column=0,3,1,2
                                        variable_name[[1,5,7,2]][:,[0,3,1,2]]   Row=2, column=0,3,1,2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [38]:
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])   


print(arr2d[[1,5,7,2]][:,[0,1,2,3]])   # Every column index will apply on every row but in Sequence.

[ 4 23 29 10]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [37]:
print(arr2d[[1,5,7,2]][:,[0,1,3,2]])

[[ 4  5  7  6]
 [20 21 23 22]
 [28 29 31 30]
 [ 8  9 11 10]]
