In [102]:
import numpy as np
import pandas as pd

In [103]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
pd1=pd.DataFrame(arr2d)
pd1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [105]:
print(pd1[:2])
print(pd1[0:2])

   0  1  2
0  1  2  3
1  4  5  6
   0  1  2
0  1  2  3
1  4  5  6


In [106]:
# array_name[starting row index:ending row index   ,    starting column index:ending column index]
print(arr2d[1,2])
'/n'
print(arr2d[0:2, 0:])

6
[[1 2 3]
 [4 5 6]]


In [107]:
a.shape

(2, 2)

In [108]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [109]:
b=arr2d[2,:]
b

array([7, 8, 9])

In [110]:
b.shape

(3,)

In [111]:
c=arr2d[2:,:]
c

array([[7, 8, 9]])

In [112]:
c.shape

(1, 3)

In [113]:
d=arr2d[:,:2]
d

array([[1, 2],
       [4, 5],
       [7, 8]])

In [114]:
d.shape

(3, 2)

In [115]:
e=arr2d[1,:2]
e

array([4, 5])

In [116]:
e.shape

(2,)

In [117]:
f=arr2d[1:2,:2]
f

array([[4, 5]])

In [118]:
f.shape

(1, 2)

In [119]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [120]:
data = np.random.randn(7, 4)
data

array([[-0.38457585, -1.09871529,  0.39020307, -1.17993115],
       [ 1.77980551,  0.86466862,  0.71169682, -1.52765933],
       [ 1.5648236 , -1.35620043, -1.42221996, -1.26908014],
       [ 1.99358042, -0.30403284, -0.46620169, -1.67725104],
       [-2.45319593,  0.72361722,  0.48663299, -0.45282775],
       [-0.85558261,  0.83803168, -0.35742757,  0.34232367],
       [ 0.84200818,  0.19967665, -0.25301779,  0.156382  ]])

In [121]:
data[0]

array([-0.38457585, -1.09871529,  0.39020307, -1.17993115])

In [122]:
names[0]

'Bob'

In [123]:
'Bob' in names    #checking the value present in the array.

True

In [124]:
names == 'Will'   #if value available then return true. otherwise return false.

array([False, False,  True, False,  True, False, False])

In [125]:
data[names == 'Bob']

array([[-0.38457585, -1.09871529,  0.39020307, -1.17993115],
       [ 1.99358042, -0.30403284, -0.46620169, -1.67725104]])

In [126]:
data[names == 'Bob', 3]   #error must be generated.

array([-1.17993115, -1.67725104])

In [127]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [128]:
 data[~(names == 'Bob')]

array([[ 1.77980551,  0.86466862,  0.71169682, -1.52765933],
       [ 1.5648236 , -1.35620043, -1.42221996, -1.26908014],
       [-2.45319593,  0.72361722,  0.48663299, -0.45282775],
       [-0.85558261,  0.83803168, -0.35742757,  0.34232367],
       [ 0.84200818,  0.19967665, -0.25301779,  0.156382  ]])

In [129]:
data < 0   # return in true or false.

array([[ True,  True, False,  True],
       [False, False, False,  True],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [False, False,  True, False]])

In [130]:
data[data<0]   # return original values.   #comparison operator (less than and greater than.)

array([-0.38457585, -1.09871529, -1.17993115, -1.52765933, -1.35620043,
       -1.42221996, -1.26908014, -0.30403284, -0.46620169, -1.67725104,
       -2.45319593, -0.45282775, -0.85558261, -0.35742757, -0.25301779])

In [131]:
data[data<0]=5   # update values in array.
data

array([[5.        , 5.        , 0.39020307, 5.        ],
       [1.77980551, 0.86466862, 0.71169682, 5.        ],
       [1.5648236 , 5.        , 5.        , 5.        ],
       [1.99358042, 5.        , 5.        , 5.        ],
       [5.        , 0.72361722, 0.48663299, 5.        ],
       [5.        , 0.83803168, 5.        , 0.34232367],
       [0.84200818, 0.19967665, 5.        , 0.156382  ]])

In [132]:
names[names != 'Joe']   #not equal  #First step

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

In [133]:
data[names != 'Joe']   #Second Step

array([[5.        , 5.        , 0.39020307, 5.        ],
       [1.5648236 , 5.        , 5.        , 5.        ],
       [1.99358042, 5.        , 5.        , 5.        ],
       [5.        , 0.72361722, 0.48663299, 5.        ]])

In [134]:
data[names != 'Joe'] = 800

In [135]:
data

array([[8.00000000e+02, 8.00000000e+02, 8.00000000e+02, 8.00000000e+02],
       [1.77980551e+00, 8.64668617e-01, 7.11696820e-01, 5.00000000e+00],
       [8.00000000e+02, 8.00000000e+02, 8.00000000e+02, 8.00000000e+02],
       [8.00000000e+02, 8.00000000e+02, 8.00000000e+02, 8.00000000e+02],
       [8.00000000e+02, 8.00000000e+02, 8.00000000e+02, 8.00000000e+02],
       [5.00000000e+00, 8.38031685e-01, 5.00000000e+00, 3.42323667e-01],
       [8.42008185e-01, 1.99676649e-01, 5.00000000e+00, 1.56382000e-01]])