In [32]:
#import numpy as np
import pandas as pd

In [33]:
a=[4, 7, -5, 3]    # List
a

[4, 7, -5, 3]

In [34]:
a1=np.array([4, 7, -5, 3])
a1

array([ 4,  7, -5,  3])

In [35]:
a2 = pd.Series([4, 2, -5, 3])
a2

0    4
1    2
2   -5
3    3
dtype: int64

In [36]:
a2.dtype

dtype('int64')

In [37]:
a2.values          # Return in numpy array.

array([ 4,  2, -5,  3])

In [38]:
print(a2.values)   # Return in numpy array.

[ 4  2 -5  3]


In [39]:
a2.index     # Stop index is exclusive.      

RangeIndex(start=0, stop=4, step=1)

In [59]:
obj2 = pd.Series([4, 7, -5, "Hussain"], index=[1,2.5,3,'Ali'])        # Index must be equal to values present in Series
obj2

1            4
2.5          7
3           -5
Ali    Hussain
dtype: object

In [60]:
obj2[2.5]

7

In [61]:
obj2.index

Index([1, 2.5, 3, 'Ali'], dtype='object')

In [62]:
obj2[2.5]= 0

In [63]:
obj2

1            4
2.5          0
3           -5
Ali    Hussain
dtype: object

In [66]:
obj2[obj2 == 'Hussain' ]

Ali    Hussain
dtype: object

In [67]:
obj2 == 'Hussain'

1      False
2.5    False
3      False
Ali     True
dtype: bool

In [68]:
'Ali' in obj2     # in operator applies on indexes not on values.

True

In [69]:
'Hussain' in obj2

False

In [70]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}   # Dict= {Key:value}
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [71]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [73]:
'Ohio' in obj3    # Points out the presence of value.

True

In [74]:
obj3['Texas']     # Return the exect value.

71000

In [88]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
states

['California', 'Ohio', 'Oregon', 'Texas']

In [89]:
obj4 = pd.Series(sdata, index=states)   # var= pd.Series(data,index)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [90]:
obj4.astype('int64')

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [91]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [92]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [96]:
result = obj3 + obj4    5000+NaN=  NaN        ,4+4=8
result

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [97]:
obj4.name = 'population'

In [99]:
obj4.index.name = 'state'

In [101]:
obj4.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [102]:
obj4

Bob          NaN
Steve    35000.0
Jeff     16000.0
Ryan     71000.0
Name: population, dtype: float64