In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.shape

(3, 5)

In [6]:
arr1=arr.T    # "Transpose" method is used to make rows as columns and columns as rows.   (changing rows and columns into one another)
arr1       # "T" refers to the Transpose of an array.   "T" must be in Capital Letter.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [7]:
arr1.shape

(5, 3)

In [8]:
arr.T==arr1.T

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [9]:
print(arr.T)
print(arr1.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
(arr.T)^T= arr      # 2^2=4    3^2=9  ,    underroot of 9 is 3     2^2^under root=2

In [10]:
arr1.T

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
arr2 = np.random.randn(6, 3)
arr2

array([[-1.55377188,  1.97629125,  0.85203818],
       [-2.17215032, -0.96172838, -0.32374042],
       [ 0.41472829,  0.26506301, -2.4256139 ],
       [-0.56270569,  1.18797454, -0.59332104],
       [-1.14912384, -0.62606552, -1.10466646],
       [-1.12125427, -1.1047167 ,  0.0467647 ]])

In [13]:
Dot_product=np.dot(arr.T, arr)
Dot_product=np.dot(arr1 , arr)       #Dot product=  np.dot(a,b)
Dot_product

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [17]:
arr3=arr*2
arr4=arr3.T
arr4

array([[ 0, 10, 20],
       [ 2, 12, 22],
       [ 4, 14, 24],
       [ 6, 16, 26],
       [ 8, 18, 28]])

In [19]:
Dot_product1=np.dot(arr4, arr)
Dot_product1

array([[250, 280, 310, 340, 370],
       [280, 316, 352, 388, 424],
       [310, 352, 394, 436, 478],
       [340, 388, 436, 484, 532],
       [370, 424, 478, 532, 586]])

In [23]:
arr4 = np.arange(16).reshape((2, 2, 4))
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [25]:
arr4.transpose((1, 0, 2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [28]:
arr4.transpose((0,1,2))


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [30]:
arr4.transpose((2,0,1))


array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [33]:
arr4.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [36]:
print(arr4)
print(arr4.swapaxes(1, 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [37]:
arr4.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [40]:
arr5 = np.arange(100)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
np.sqrt(arr5)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [45]:
np.exp(arr5)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
      

In [53]:
np.exp(1)     # square of 1 is 1 but exponent in numpy that is also 1^1 not equal to 1 but equal to a pre-defined value.
              # Exponent value is pre-defined =   2.718281828459045             (exp)^2 =   (2.718281828459045)^2=7.38905609893065

2.718281828459045

In [55]:
np.exp(2)      # square 2*2=4       exp= 2^exponent^2=4    2^exp^2=7

7.38905609893065

In [56]:
np.exp(3)     

20.085536923187668

In [57]:
np.exp(4)

54.598150033144236

In [50]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)

[ 0.98696975  1.48371047  0.02066656  1.14787674 -0.31134493  1.12952623
  1.18768964 -0.06717214]
[ 0.0883295   0.74033994  0.36554893  1.01175029 -0.01812598  1.45220765
 -1.1734591   0.91236637]


In [58]:
np.maximum(x, y)

array([ 0.98696975,  1.48371047,  0.36554893,  1.14787674, -0.01812598,
        1.45220765,  1.18768964,  0.91236637])

In [59]:
arr6 = np.random.randn(7) * 5
arr6

array([ -7.11720876,  -2.16384064,   0.3224499 ,  -1.83166687,
        -1.69224613,  -0.08649724, -10.21114085])

In [60]:
remainder, whole_part = np.modf(arr6)

In [61]:
remainder

array([-0.11720876, -0.16384064,  0.3224499 , -0.83166687, -0.69224613,
       -0.08649724, -0.21114085])

In [62]:
whole_part

array([ -7.,  -2.,   0.,  -1.,  -1.,  -0., -10.])