In [27]:
import numpy as np

In [28]:
points = np.arange(-5, 5, 0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [29]:
xs, ys = np.meshgrid(points, points)

In [30]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [8]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [31]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [32]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [33]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [34]:
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
   for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [35]:
result1 = np.where(cond, xarr, yarr)
result1

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [49]:
arr1 = np.random.randn(4, 4)
arr1

array([[-0.53464451, -2.07068904, -0.9375706 ,  1.12056273],
       [-0.31069085, -1.18137473, -0.58261285, -0.96837756],
       [-1.48052507,  0.79278937,  0.01992167, -0.0686209 ],
       [-1.15914756, -0.6306403 , -0.82437302, -1.67593302]])

In [50]:
arr1>6

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [51]:
arr1==-1.15914756     #   The value that is corresponding to -1.15914756 is must be True.

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [56]:
arr2=np.where(arr1> 0, 2, -2)      # condition will apply where, value will be replaced with 2 otherwise where condition 
                                   # is true the value will be replaced by -2.
arr2

array([[-2, -2, -2,  2],
       [-2, -2, -2, -2],
       [-2,  2,  2, -2],
       [-2, -2, -2, -2]])

In [53]:
arr > 0, 2, -2

(array([[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False,  True,  True,  True],
        [ True,  True, False,  True]]), 2, -2)

In [ ]:
np.where(arr > 0, 2, arr)

In [57]:
np.where(arr1>0,2,arr1 )           # condition will apply where, value will be replaced with 2 otherwise where condition 
                                   # is true the value will be replaced by arr1.

array([[-0.53464451, -2.07068904, -0.9375706 ,  2.        ],
       [-0.31069085, -1.18137473, -0.58261285, -0.96837756],
       [-1.48052507,  2.        ,  2.        , -0.0686209 ],
       [-1.15914756, -0.6306403 , -0.82437302, -1.67593302]])

In [63]:
arr3=np.where(arr1> 0, True, False)    
arr3

array([[False, False, False,  True],
       [False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [64]:
arr3.dtype

dtype('bool')

In [70]:
arr4=np.where(arr1> 0, 5,-5)    
arr4

array([[-5, -5, -5,  5],
       [-5, -5, -5, -5],
       [-5,  5,  5, -5],
       [-5, -5, -5, -5]])

In [72]:
arr4.dtype

dtype('int64')

In [66]:
arr4.dtype

dtype('<U5')